version: '1.0'

services:
    eureka-sv:
        build: eureka-sv
        mem_limit: 512m
        container_name: eureka-sv
        ports:
            - "8761:8761"
        networks:
            - 'microelectro-network'
    product-service:
        build: product-service
        mem_limit: 512m
        container_name: product-service
        ports:
            - "9001:9001"
        networks:
            - 'microelectro-network'
        environment:
            DB_URL_PRODUCT: jdbc:mysql://db:3307/product_service?createDatabaseIfNotExist=true&serverTimezone=UTC
            DB_USER_NAME: root
            DB_PASSWORD: root
            SERV_URL: http://eureka-sv:8761/eureka
        depends_on:
            db:
                condition: service_healthy
    cart-service:
        build: cart-service
        mem_limit: 512m
        container_name: cart-service
        ports:
            - "9002:9002"
        networks:
            - 'microelectro-network'
        environment:
            DB_URL_CART: jdbc:mysql://db:3307/cart_service?createDatabaseIfNotExist=true&serverTimezone=UTC
            DB_USER_NAME: root
            DB_PASSWORD: root
            SERV_URL: http://eureka-sv:8761/eureka
        depends_on:
            db:
                condition: service_healthy
    sale-service:
        build: sale-service
        mem_limit: 512m
        container_name: sale-service
        ports:
            - "9003:9003"
        networks:
            - 'microelectro-network'
        environment:
            DB_URL_SALE: jdbc:mysql://db:3307/sale_service?createDatabaseIfNotExist=true&serverTimezone=UTC
            DB_USER_NAME: root
            DB_PASSWORD: root
            SERV_URL: http://eureka-sv:8761/eureka
        depends_on:
            db:
                condition: service_healthy
    api-gateway-electro:
        build: api-gateway-electro
        mem_limit: 512m
        container_name: api-gateway-electro
        ports:
            - "443:443"
        depends_on:
            - sale-service
            - cart-service
            - product-service
            - eureka-sv
        environment:
            URI_PRODUCT: lb://product-service
            URI_CART: lb://cart-service
            URI_SALE: lb://sale-service
            DEFAULT_ZONE: http://eureka-sv:8761/eureka
        networks:
            - 'microelectro-network'
    db:
        image: mysql:9.0.0
        container_name: db
        ports:
            - "3307:3307"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_TCP_PORT: 3307

        volumes:
          - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
        restart: always
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            timeout: 10s
            retries: 3
        networks:
            - 'microelectro-network'
networks:
    microelectro-network:
